#! /bin/sh

# Autostart
pgrep -x sxhkd >/dev/null || sxhkd &
sh ~/.fehbg &
xsetroot -cursor_name left_ptr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
clipmenud &
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

# Рамки и гапсы
bspc config border_width 1
bspc config window_gap 5

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"

# Цвет пространства при выборе положения нового окна
bspc config presel_feedback_color "#f38ba8"

# Кофициент разделения окна
bspc config split_ratio 1.0

# Фокус окна наведением курсора
bspc config focus_follows_pointer false
bspc config pointer_modifier super

# Режим монокля когда открыто одно окно
bspc config single_monocle false

# Отключение гапсов рамок и отступов когда открыто одно окно
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config paddingless_monocle true

# Правила
bspc rule -a floating-app state=floating center=on
bspc rule -a TelegramDesktop state=floating
bspc rule -a Thunar state=floating
