general.import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = 'xterm-256color'
EDITOR = 'nvim'

[terminal]
shell='tmux'

[font]
normal.family = 'JetBrainsMono Nerd Font'
size = 12

[window]
padding.x = 10
padding.y = 10
